apiVersion: v2
appVersion: v0.0.1
description: A web interface for Sealed Secrets by Bitnami.
home: https://github.com/bakito/sealed-secrets-web
icon: https://raw.githubusercontent.com/bakito/sealed-secrets-web/master/assets/logo.png
maintainers:
  - name: bakito
    url: https://github.com/bakito
name: sealed-secrets-web
version: 0.0.1
sources:
  - https://github.com/bakito/sealed-secrets-web
