{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "sealed-secrets-web.fullname" . }}
  labels:
{{ include "sealed-secrets-web.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealed-secrets-web
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ template "sealed-secrets-web.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
