version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: k8s.io/client-go
      - dependency-name: k8s.io/apimachinery
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
