version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
        update-types:
          - "minor"
          - "patch"
      onsi:
        patterns:
          - "github.com/onsi/*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
