apiVersion: v1
appVersion: 1.1.0
description: A web interface for Sealed Secrets by Bitnami.
home: https://github.com/ricoberger/sealed-secrets-web
icon: https://raw.githubusercontent.com/ricoberger/sealed-secrets-web/master/assets/logo.png
maintainers:
  - name: Rico Berger
    url: https://ricoberger.de
name: sealed-secrets-web
version: 1.1.0
