replicaCount: 1

image:
  repository: ghcr.io/bakito/sealed-secrets-web
  # default version .Chart.AppVersion
  tag:
  pullPolicy: IfNotPresent
  args: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  name: sealed-secrets-web

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sealed-secrets-web.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  # set this to true and leave tls an empty array to use the default TLS certificate (works at least in openshift)
  defaultTls: false
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
