replicaCount: 1

image:
  repository: ricoberger/sealed-secrets-web
  tag: 2.2.1
  pullPolicy: IfNotPresent
  args: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  name: sealed-secrets-web

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: sealed-secrets-web.local
      paths: []

  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
