# -- The number of pods to run
replicaCount: 1
# -- If set to true, the application has only the permission to view sealed secrets in the current namespace
includeLocalNamespaceOnly: false

# -- If set to true secrets cannot be read from this tool, only seal new ones
disableLoadSecrets: false

# -- Secret format - either json or yaml
format: yaml

sealedSecrets:
  # -- Namespace of the sealed secrets service
  namespace: sealed-secrets
  # -- Name of the sealed secrets service
  serviceName: sealed-secrets
  # -- URL sealed secrets certificate (required if sealed secrets is not reachable with in cluster service)
  certURL: """

image:
  # --  Repository to use
  repository: ghcr.io/bakito/sealed-secrets-web
  # -- Overrides the image tag (default is the chart appVersion)
  tag:
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Additional command args
  args: [ ]
  # - "--kubeseal-arguments=--controller-name=sealed-secrets"

# -- Secrets with credentials to pull images from a private registry. Registry secret names as an array.
imagePullSecrets: [ ]

# -- String to partially override "argo-rollouts.fullname" template
nameOverride: ""

# -- String to fully override "argo-rollouts.fullname" template
fullnameOverride: ""

rbac:
  # -- Specifies whether rbac should be created
  create: true

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use.
  name: sealed-secrets-web

service:
  # -- Sets the type of the Service
  type: ClusterIP
  # -- Service port
  port: 80

ingress:
  # -- Enable ingress support
  enabled: false

  # -- Ingress class name
  className: ""
  # -- Ingress annotations
  annotations: { }
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  # nginx.ingress.kubernetes.io/use-regex: "true"
  # -- Ingress hosts
  hosts: [ ]
    #- paths:
  #    - path: /ssw(/|$)(.*)
  #      pathType: Prefix
  # -- set this to true and leave tls an empty array to use the default TLS certificate (works at least in openshift)
  defaultTls: false
  # -- Ingress tls
  tls: [ ]

# -- Resource limits and requests for the pods.
resources: { }
  # limits:
  #   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi


# -- [Node selector]
nodeSelector: { }

# -- [Tolerations] for use with node taints
tolerations: [ ]

# -- Assign custom [affinity] rules to the deployment
affinity: { }
