{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.includeLocalNamespaceOnly }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ template "sealed-secrets-web.fullname" . }}
{{- if .Values.includeLocalNamespaceOnly }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
{{ include "sealed-secrets-web.labels" . | indent 4 }}
rules:
{{- if not .Values.disableLoadSecrets }}
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
{{- end }}
  - apiGroups:
      - ""
    resources:
      - services/proxy
    verbs:
      - get
    resourceNames:
      - {{ .Values.sealedSecrets.serviceName }}

---

apiVersion: rbac.authorization.k8s.io/v1
{{ if .Values.includeLocalNamespaceOnly }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ template "sealed-secrets-web.fullname" . }}
{{- if .Values.includeLocalNamespaceOnly }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
{{ include "sealed-secrets-web.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{ if .Values.includeLocalNamespaceOnly }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ template "sealed-secrets-web.fullname" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ template "sealed-secrets-web.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
