{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sealed-secrets-web.serviceAccountName" . }}
  labels:
{{ include "sealed-secrets-web.labels" . | indent 4 }}
{{ end }}
