// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bitnami-labs/sealed-secrets/pkg/client/clientset/versioned/typed/sealedsecrets/v1alpha1 (interfaces: BitnamiV1alpha1Interface,SealedSecretInterface)
//
// Generated by this command:
//
//	mockgen -destination pkg/mocks/ssclient/mock.go --package ssclient github.com/bitnami-labs/sealed-secrets/pkg/client/clientset/versioned/typed/sealedsecrets/v1alpha1 BitnamiV1alpha1Interface,SealedSecretInterface
//

// Package ssclient is a generated GoMock package.
package ssclient

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/apis/sealedsecrets/v1alpha1"
	v1alpha10 "github.com/bitnami-labs/sealed-secrets/pkg/client/clientset/versioned/typed/sealedsecrets/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MockBitnamiV1alpha1Interface is a mock of BitnamiV1alpha1Interface interface.
type MockBitnamiV1alpha1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockBitnamiV1alpha1InterfaceMockRecorder
}

// MockBitnamiV1alpha1InterfaceMockRecorder is the mock recorder for MockBitnamiV1alpha1Interface.
type MockBitnamiV1alpha1InterfaceMockRecorder struct {
	mock *MockBitnamiV1alpha1Interface
}

// NewMockBitnamiV1alpha1Interface creates a new mock instance.
func NewMockBitnamiV1alpha1Interface(ctrl *gomock.Controller) *MockBitnamiV1alpha1Interface {
	mock := &MockBitnamiV1alpha1Interface{ctrl: ctrl}
	mock.recorder = &MockBitnamiV1alpha1InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBitnamiV1alpha1Interface) EXPECT() *MockBitnamiV1alpha1InterfaceMockRecorder {
	return m.recorder
}

// RESTClient mocks base method.
func (m *MockBitnamiV1alpha1Interface) RESTClient() rest.Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RESTClient")
	ret0, _ := ret[0].(rest.Interface)
	return ret0
}

// RESTClient indicates an expected call of RESTClient.
func (mr *MockBitnamiV1alpha1InterfaceMockRecorder) RESTClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RESTClient", reflect.TypeOf((*MockBitnamiV1alpha1Interface)(nil).RESTClient))
}

// SealedSecrets mocks base method.
func (m *MockBitnamiV1alpha1Interface) SealedSecrets(arg0 string) v1alpha10.SealedSecretInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SealedSecrets", arg0)
	ret0, _ := ret[0].(v1alpha10.SealedSecretInterface)
	return ret0
}

// SealedSecrets indicates an expected call of SealedSecrets.
func (mr *MockBitnamiV1alpha1InterfaceMockRecorder) SealedSecrets(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SealedSecrets", reflect.TypeOf((*MockBitnamiV1alpha1Interface)(nil).SealedSecrets), arg0)
}

// MockSealedSecretInterface is a mock of SealedSecretInterface interface.
type MockSealedSecretInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSealedSecretInterfaceMockRecorder
}

// MockSealedSecretInterfaceMockRecorder is the mock recorder for MockSealedSecretInterface.
type MockSealedSecretInterfaceMockRecorder struct {
	mock *MockSealedSecretInterface
}

// NewMockSealedSecretInterface creates a new mock instance.
func NewMockSealedSecretInterface(ctrl *gomock.Controller) *MockSealedSecretInterface {
	mock := &MockSealedSecretInterface{ctrl: ctrl}
	mock.recorder = &MockSealedSecretInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSealedSecretInterface) EXPECT() *MockSealedSecretInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSealedSecretInterface) Create(arg0 context.Context, arg1 *v1alpha1.SealedSecret, arg2 v1.CreateOptions) (*v1alpha1.SealedSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.SealedSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSealedSecretInterfaceMockRecorder) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSealedSecretInterface)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockSealedSecretInterface) Delete(arg0 context.Context, arg1 string, arg2 v1.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSealedSecretInterfaceMockRecorder) Delete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSealedSecretInterface)(nil).Delete), arg0, arg1, arg2)
}

// DeleteCollection mocks base method.
func (m *MockSealedSecretInterface) DeleteCollection(arg0 context.Context, arg1 v1.DeleteOptions, arg2 v1.ListOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockSealedSecretInterfaceMockRecorder) DeleteCollection(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockSealedSecretInterface)(nil).DeleteCollection), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockSealedSecretInterface) Get(arg0 context.Context, arg1 string, arg2 v1.GetOptions) (*v1alpha1.SealedSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.SealedSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSealedSecretInterfaceMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSealedSecretInterface)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockSealedSecretInterface) List(arg0 context.Context, arg1 v1.ListOptions) (*v1alpha1.SealedSecretList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*v1alpha1.SealedSecretList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSealedSecretInterfaceMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSealedSecretInterface)(nil).List), arg0, arg1)
}

// Patch mocks base method.
func (m *MockSealedSecretInterface) Patch(arg0 context.Context, arg1 string, arg2 types.PatchType, arg3 []byte, arg4 v1.PatchOptions, arg5 ...string) (*v1alpha1.SealedSecret, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*v1alpha1.SealedSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockSealedSecretInterfaceMockRecorder) Patch(arg0, arg1, arg2, arg3, arg4 any, arg5 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockSealedSecretInterface)(nil).Patch), varargs...)
}

// Update mocks base method.
func (m *MockSealedSecretInterface) Update(arg0 context.Context, arg1 *v1alpha1.SealedSecret, arg2 v1.UpdateOptions) (*v1alpha1.SealedSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.SealedSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSealedSecretInterfaceMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSealedSecretInterface)(nil).Update), arg0, arg1, arg2)
}

// UpdateStatus mocks base method.
func (m *MockSealedSecretInterface) UpdateStatus(arg0 context.Context, arg1 *v1alpha1.SealedSecret, arg2 v1.UpdateOptions) (*v1alpha1.SealedSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.SealedSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSealedSecretInterfaceMockRecorder) UpdateStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSealedSecretInterface)(nil).UpdateStatus), arg0, arg1, arg2)
}

// Watch mocks base method.
func (m *MockSealedSecretInterface) Watch(arg0 context.Context, arg1 v1.ListOptions) (watch.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0, arg1)
	ret0, _ := ret[0].(watch.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockSealedSecretInterfaceMockRecorder) Watch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockSealedSecretInterface)(nil).Watch), arg0, arg1)
}
