# The 'apiVersion' and 'kind' should always be 'v1' and 'Secret'.
apiVersion: v1
kind: Secret
# Metadata section of the secret.
# The encoding and decoding function only uses the 'name', 'namespace', 'annotations'
# and 'labels' field.
# All other fields will be striped during the encoding / decoding.
metadata:
  name: mysecretname
  namespace: mysecretnamespace
# All fields in the 'stringData' section will be encoded, decoded or encrypted.
stringData:
  username: admin
  password: admin
  values.yaml: |
    secretName: mysecretname
    secretValue: mysecretvalue
    subSecrets:
      key: value
# The type of the Secret can be any valid Kubernetes secret type.
# Normally this should be 'Opaque'.
type: Opaque
