name: Docker
on: [release]
jobs:
  build-release:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Package Registry
      run: docker login docker.pkg.github.com --username ricoberger --password ${{ secrets.TOKEN }}

    - name: Release
      run: make release
