name: end-2-end Helm Chart Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🖼 Build image
        run: ./testdata/e2e/image-01-build-and-save.sh

      - name: 📦 Upload image tar
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: image-tar
          path: /tmp/image.tar
          retention-days: 1

  e2e:
    needs: build-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://hub.docker.com/r/kindest/node/tags
        k8s_version: [ "v1.33.7", "v1.34.3", "v1.35.1"]
        format: [ "yaml", "json" ]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install kind with registry
        uses: bakito/kind-with-registry-action@9c031e8b0c6f20fec65ca5a58901d05e585ff5d0 # v1.0.0
        with:
          kind_cluster_name: e2e
          node_image: kindest/node:${{ matrix.k8s_version }}
          kubectl_version: ${{ matrix.k8s_version }}
          debug: false
      - name: ⚙️ Check Chart with Chainsaw
        run: ./testdata/e2e/chainsaw/run.sh

      - name: 📥 Download image tar
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: image-tar
          path: /tmp

      - name: 🖼 Load image
        run: ./testdata/e2e/image-02-load-and-push.sh

      - name: Install sealed-secrets
        run: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
          helm install sealed-secrets sealed-secrets/sealed-secrets \
            --namespace sealed-secrets \
            --create-namespace \
            --wait=watcher

      - name: 🏠 Install sealed-secrets-web with ${{ matrix.format }} format In-Cluster
        run: ./testdata/e2e/installSealedSecretsWebChart.sh ${{ matrix.format }} ""

      - name: 🏠 Run Tests In-Cluster
        id: run_tests_in_cluster
        # continue on error to show logs
        continue-on-error: true
        working-directory: testdata/e2e
        run: ./runTests.sh

      - name: 🏠 Print logs In-Cluster
        run: |
          echo '🏠 Pod logs (${{ matrix.format }} format In-Cluster)' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          POD_NAME=$(kubectl get pod -n sealed-secrets-web -l app.kubernetes.io/instance=sealed-secrets-web  -o name)
          kubectl logs -n sealed-secrets-web ${POD_NAME} >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: 🏠 Fail if 'Run Tests In-Cluster' failed
        if: steps.run_tests_in_cluster.outcome=='failure'
        run: |
          echo "Step 'Run Tests In-Cluster' failed: Check 'Run Tests In-Cluster' and 'Print logs In-Cluster' as well as the job summary for errors"
          exit 1

      - name: 🔐 Install sealed-secrets-web with ${{ matrix.format }} format and cert URL
        run: |
          helm delete sealed-secrets-web --namespace sealed-secrets-web
          ./testdata/e2e/installSealedSecretsWebChart.sh ${{ matrix.format }} http://sealed-secrets.sealed-secrets.svc:8080/v1/cert.pem

      - name: 🔐 Run Tests Cert-URL
        id: run_tests_certURL
        # continue on error to show logs
        continue-on-error: true
        working-directory: testdata/e2e
        run: ./runTests.sh skip-validate

      - name: 🔐 Print logs Cert-URL
        run: |
          echo '🔐 Pod logs (${{ matrix.format }} format and Cert-URL)' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          POD_NAME=$(kubectl get pod -n sealed-secrets-web -l app.kubernetes.io/instance=sealed-secrets-web  -o name)
          kubectl logs -n sealed-secrets-web ${POD_NAME} >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: 🔐 Fail if 'Run Tests Cert-URL' failed
        if: steps.run_tests_certURL.outcome=='failure'
        run: |
          echo "Step 'Run Tests Cert-URL' failed: Check 'Run Tests Cert-URL' and 'Print logsCert-URL' as well as the job summary for errors"
          exit 1
