name: Build images

on:
  push:
    branches:
      - kind-tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.14.0
          kubectl_version: v1.24.0
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Install sealed-secrets
        run: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
          helm install sealed-secrets sealed-secrets/sealed-secrets \
            --namespace sealed-secrets \
            --create-namespace \
            --atomic
      - name: Install sealed-secrets
        run: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
          helm install sealed-secrets-web  charts/sealed-secrets-web \
            --namespace sealed-secrets-web \
            --create-namespace \
            --set image.tag=main \
            --atomic
