name: prune-images

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.PRUNE_IMAGE_TOKEN }}
          container: sealed-secrets-web
          dry-run: false # Dry-run first, then change to `false`
          older-than: 7 # days
          untagged: true
