name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Test
        run: make test-cover

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverprofile.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  helm:
    name: Helm Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Set up Tools
        run: make semver helm-docs

      - name: Lint
        run: make helm-lint

      - name: Check chart/README.md is correctly generated with 'make docs'
        run: git diff --exit-code chart/README.md

      - name: Template
        run: make helm-template
